### PR TITLE
Added arrow keys controls

### PR DESCRIPTION
**Pull request by hissssst**
Simply added arrow keys controls. I am currently thinking of way to make theese keys configurable. But thats it for now

### CODE REVIEW

**Comment by Vifon** [comment]
Sorry for a late response.

Won't this catch any unbound key followed by any key and then A/B/C/D?

**Comment by hissssst** [comment]
> Sorry for a late response.
> 
> Won't this catch any unbound key followed by any key and then A/B/C/D?

Yes, it will. I wrote it that way because I hadn't knew how to match an escape character. I am still thinking of the way to hack it so it won't catch any character

**Comment by hissssst** [comment]
It is possible to add the same `case` in the `*)` part of case, like recursive. It will help to deal with arrows, but code will look *really nasty*

**Comment by Vifon** [comment]
> It is possible to add the same case in the *) part of case, like recursive. It will help to deal with arrows, but code will look really nasty

Yes (possible) and yes (nasty). To make it recursive you can wrap the whole `case` in a function.

I was thinking about nested `case`, first the existing one matching `\e`, the second layer `[` and the third layer matching A/B/C/D. It would be pretty nasty too though. :/

I think the proper way to handle it is to make use of the actual zsh keymaps but I never found the time to adjust the code. If you're feeling up to the task feel free to do so.

**Comment by hissssst** [comment]
I've added escape character matching and modified pointing arrow (if you don't mind :\).
Although, there is one problem. Pressing `<ESC>` key causes program to freeze for next two key presses

**Comment by Vifon** [comment]
@hissssst 
I reverted your last commit as I'd rather not include multiple separate changes in a single PR. I don't mind changing the arrow, just submit it as a second PR. :)

After my changes, it should only eat up one character after <kbd>Esc</kbd>, which is pretty common and expected.

Thanks!

**Comment by hissssst** [comment]
@Vifon 
Nicely done. I think I won't make PR about `->` because it is not necessary

**Pull request merged**
